### ISSUE TITLE
How to bind layot_corrector.sh to a key 'Scroll Lock'

### ISSUE THREAD

**Issue by ghost** [Hukuta/layout_corrector#1]
Hello!

Can you describe how to bind layout_corrector/layot_corrector.sh to a key 'Scroll Lock'.

**Comment by coffebar** [comment]
i'm using Settings of my desktop env. 
In XFCE Menu: Settings -> Keyboard -> Application Shortcuts 
```
Command: YourPath/layot_corrector.sh
Shortcut: Scroll Lock
```

**Comment by ghost** [comment]
Thank you for your quick and clear answer.

I am using `i3`. Found in internet, that I can use program `xbindkeys`.

1. install `xbindkeys`

    ```
    sudo apt install xbindkeys
    ```

2. create config file `~/.xbindkeysrc`

    ```
    vim ~/.xbindkeysrc
    ```

3. add to config file `~/.xbindkeysrc`

    ```
    "/home/user/bin/layout_corrector/layot_corrector.sh"
    Scroll_Lock
    ```

4. add `xbindkeys` to autostart. For `i3` you can add this to file `~/.config/i3/config`:

    ```
    exec --no-startup-id "xbindkeys -f /home/user/.xbindkeysrc"
    ```
